### ISSUE TITLE
Antworträume zu klein/eng seit Commit e29efd7e5a92e0a3cc5af771f6048d26380186e2

### ISSUE THREAD

**Issue by berb** [vs-uulm/latex-lecture-templates#23]
Ein zu kleiner Antwortraum (z.B. kleiner Linienabstand) macht handschriftliche Antworten noch schwerer zu lesen.

**Comment by berb** [comment]
Invalid.

**Comment by namnatulco** [comment]
Könnte mann die höhe (also zwischen den Spalten) nicht erhöhen, bzw. konfigurierbar machen?
